"""add fundbuero_id

Revision ID: 1cc4b53c6117
Revises: 
Create Date: 2026-07-16 01:59:57.887636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc4b53c6117'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standardUser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fundbuero_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_standarduser_fundbuero_id', 'fundbuero', ['fundbuero_id'], ['fundbuero_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standardUser', schema=None) as batch_op:
        batch_op.drop_constraint('fk_standarduser_fundbuero_id', type_='foreignkey')
        batch_op.drop_column('fundbuero_id')

    # ### end Alembic commands ###
